; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][subdir] = "contrib"
projects[drupal][version] = "7.34"
projects[drupal][type] = "core"

; Profiles
projects[rune][type] = "profile"
projects[rune][download][url] = "https://github.com/RealLukeMartin/rune.git"
projects[rune][download][type] = "git"
projects[rune][download][branch] = "retro"